# --- Coverage 제외 ---
sonar.coverage.exclusions=\
**/src/pages/**,\
**/src/shared/ui/**,\
**/src/shared/layout/**,\
**/src/shared/auth/auth-provider.tsx,\
**/src/shared/auth/require-auth.tsx,\
**/src/shared/lib/auth.ts,\
**/src/shared/lib/use-activity-gallery.ts,\
**/src/shared/auth/auth-context.tsx,\
**/src/shared/auth/use-auth.tsx,\
**/src/shared/api/fetch-with-access.ts,\
**/src/shared/lib/use-pagination.ts

# --- Duplication(CPD) 제외 ---
sonar.cpd.exclusions=\
**/src/pages/activities/**/lib/data.ts